In [127]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [128]:
df = pd.read_csv("dataset/16-diabetes.csv")

In [129]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [130]:
df.shape

(768, 9)

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [132]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000


In [133]:
df.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000


In [134]:
df['Insulin'].value_counts()

Insulin
0      374
105     11
130      9
140      9
120      8
      ... 
73       1
171      1
255      1
52       1
112      1
Name: count, Length: 186, dtype: int64

In [135]:
df['BloodPressure'].value_counts()

BloodPressure
70     57
74     52
78     45
68     45
72     44
64     43
80     40
76     39
60     37
0      35
62     34
66     30
82     30
88     25
84     23
90     22
86     21
58     21
50     13
56     12
52     11
54     11
75      8
92      8
65      7
85      6
94      6
48      5
96      4
44      4
100     3
106     3
98      3
110     3
55      2
108     2
104     2
46      2
30      2
122     1
95      1
102     1
61      1
24      1
38      1
40      1
114     1
Name: count, dtype: int64

In [136]:
df['SkinThickness'].value_counts()

SkinThickness
0     227
32     31
30     27
27     23
23     22
33     20
28     20
18     20
31     19
19     18
39     18
29     17
40     16
25     16
26     16
22     16
37     16
41     15
35     15
36     14
15     14
17     14
20     13
24     12
42     11
13     11
21     10
46      8
34      8
12      7
38      7
11      6
43      6
16      6
45      6
14      6
44      5
10      5
48      4
47      4
49      3
50      3
8       2
7       2
52      2
54      2
63      1
60      1
56      1
51      1
99      1
Name: count, dtype: int64

In [137]:
df["Pregnancies"].value_counts()

Pregnancies
1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: count, dtype: int64

In [138]:
import numpy as np
from sklearn.model_selection import train_test_split

df = df[df['BloodPressure'] != 0]


X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Train-Test Split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15)


columns_to_fix = ["Glucose", "BMI","SkinThickness","Insulin"]

for col in columns_to_fix:
    # SADECE X_train içindeki 0 olmayan değerlerin medyanını buluyoruz
    train_median = X_train[X_train[col] != 0][col].median()
    
    # Bu medyan değerini kullanarak hem Train hem de Test setini dolduruyoruz
    X_train[col] = X_train[col].replace(0, train_median)
    X_test[col] = X_test[col].replace(0, train_median)




LOGİSTİC REGRESYON

In [139]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

logistic_regresyon =LogisticRegression()

logistic_regresyon_param = {
    "penalty": ["l1", "l2", "elasticnet", None], 
    "C": [0.1, 1, 10, 100],                       
    "solver": ["liblinear", "saga"]              
}

grid=GridSearchCV(estimator=logistic_regresyon,cv=3,param_grid=logistic_regresyon_param,n_jobs=-1,verbose=1)


grid.fit(X_train,y_train)


# 1. En iyi parametreleri gör (C, penalty ve solver hangisi seçildi?)
print("En iyi parametreler:", grid.best_params_)

# 2. En iyi skoru gör (Başarı oranı kaç?)
print("En iyi skor:", grid.best_score_)

# 3. En iyi modeli doğrudan al ve kullan
en_iyi_model = grid.best_estimator_

Fitting 3 folds for each of 32 candidates, totalling 96 fits
En iyi parametreler: {'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}
En iyi skor: 0.7833420547706261


C:\Users\PC\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
36 fits failed out of a total of 96.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\PC\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\PC\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver

In [140]:
logistic_regresyon =LogisticRegression(C=1,penalty="l1",solver="liblinear")

logistic_regresyon.fit(X_train,y_train)
y_pred_logistic=logistic_regresyon.predict(X_test)

In [141]:
print(classification_report(y_test, y_pred_logistic))
print(accuracy_score(y_test, y_pred_logistic))
print(confusion_matrix(y_test, y_pred_logistic))

              precision    recall  f1-score   support

           0       0.74      0.81      0.77        91
           1       0.64      0.54      0.58        56

    accuracy                           0.71       147
   macro avg       0.69      0.67      0.68       147
weighted avg       0.70      0.71      0.70       147

0.7074829931972789
[[74 17]
 [26 30]]


Destek Vektör Makineleri

In [142]:
from sklearn import svm
svc_classifier=svm.LinearSVC()

svc_classifier_param = {
    "penalty": ["l2"],            # LinearSVC'de çoğu durumda l2 kullanılır
    "loss": ["hinge", "squared_hinge"], 
    "C": [0.1, 1, 5, 10],         # 0 yerine 0.1 gibi küçük bir değerle başla
    "class_weight": ["balanced", None],
    "max_iter": [2000]            # Yakınsama (convergence) hatası almamak için artırmak iyidir
}

grid=GridSearchCV(estimator=svc_classifier,cv=3,param_grid=svc_classifier_param,n_jobs=-1,verbose=1)

grid.fit(X_train,y_train)

# 1. En iyi parametreleri gör (C, penalty ve solver hangisi seçildi?)
print("En iyi parametreler:", grid.best_params_)

# 2. En iyi skoru gör (Başarı oranı kaç?)
print("En iyi skor:", grid.best_score_)

# 3. En iyi modeli doğrudan al ve kullan
en_iyi_model = grid.best_estimator_

Fitting 3 folds for each of 16 candidates, totalling 48 fits
En iyi parametreler: {'C': 10, 'class_weight': None, 'loss': 'squared_hinge', 'max_iter': 2000, 'penalty': 'l2'}
En iyi skor: 0.7867521367521367


In [143]:
svc_classifier=svm.LinearSVC(C=10,class_weight=None,loss="squared_hinge",max_iter=2000,penalty="l2")

svc_classifier.fit(X_train,y_train)
y_pred_svc=svc_classifier.predict(X_test)

print(classification_report(y_test, y_pred_svc))
print(accuracy_score(y_test, y_pred_svc))
print(confusion_matrix(y_test, y_pred_svc))

              precision    recall  f1-score   support

           0       0.74      0.82      0.78        91
           1       0.65      0.54      0.59        56

    accuracy                           0.71       147
   macro avg       0.70      0.68      0.68       147
weighted avg       0.71      0.71      0.71       147

0.7142857142857143
[[75 16]
 [26 30]]


BernoulliNB

In [144]:
from sklearn.naive_bayes import BernoulliNB
nb_bernoulli=BernoulliNB()
bernoulli_nb_param = {
    'alpha': [0.01, 0.1, 0.5, 1.0, 10.0], # Laplace düzeltmesi (Smoothing)
    'binarize': [0.0, 0.5, 1.0]           # Sayıları 0/1 yapmak için eşik değeri
}
grid_bnb = GridSearchCV(estimator=nb_bernoulli, param_grid=bernoulli_nb_param, cv=3, n_jobs=-1, verbose=1)
grid_bnb.fit(X_train,y_train)

# 1. En iyi parametreleri gör (C, penalty ve solver hangisi seçildi?)
print("En iyi parametreler:", grid_bnb.best_params_)

# 2. En iyi skoru gör (Başarı oranı kaç?)
print("En iyi skor:", grid_bnb.best_score_)

# 3. En iyi modeli doğrudan al ve kullan
en_iyi_model = grid_bnb.best_estimator_

Fitting 3 folds for each of 15 candidates, totalling 45 fits
En iyi parametreler: {'alpha': 0.01, 'binarize': 1.0}
En iyi skor: 0.6706610849467992


In [145]:
nb_bernoulli=BernoulliNB(alpha=0.01, binarize=1.0)

nb_bernoulli.fit(X_train,y_train)
y_pred_svc=nb_bernoulli.predict(X_test)

print(classification_report(y_test, y_pred_svc))
print(accuracy_score(y_test, y_pred_svc))
print(confusion_matrix(y_test, y_pred_svc))

              precision    recall  f1-score   support

           0       0.64      0.98      0.78        91
           1       0.78      0.12      0.22        56

    accuracy                           0.65       147
   macro avg       0.71      0.55      0.50       147
weighted avg       0.70      0.65      0.56       147

0.6530612244897959
[[89  2]
 [49  7]]


KNeighborsClassifier 

In [146]:
from sklearn.neighbors import KNeighborsClassifier

knn_param = {
    "n_neighbors": [3, 5, 7, 9, 11, 15], # Bakılacak komşu sayısı
    "weights": ["uniform", "distance"],  # Komşuların ağırlığı (Eşit veya Mesafeye göre)
    "metric": ["euclidean", "manhattan"] # Mesafe hesaplama yöntemi
}

knn = KNeighborsClassifier()

grid_knn = GridSearchCV(
    estimator=knn,
    param_grid=knn_param,
    cv=3, 
    n_jobs=-1, 
    verbose=1
)

grid_knn.fit(X_train, y_train)

print("En iyi KNN parametreleri:", grid_knn.best_params_)
print("En iyi KNN skoru:", grid_knn.best_score_)

Fitting 3 folds for each of 24 candidates, totalling 72 fits
En iyi KNN parametreleri: {'metric': 'euclidean', 'n_neighbors': 15, 'weights': 'distance'}
En iyi KNN skoru: 0.7594191522762951


In [147]:
knn = KNeighborsClassifier(metric="euclidean",n_neighbors=15,weights="distance")
knn.fit(X_train,y_train)
y_pred_knn=knn.predict(X_test)

print(classification_report(y_test, y_pred_knn))
print(accuracy_score(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.76      0.81      0.78        91
           1       0.65      0.57      0.61        56

    accuracy                           0.72       147
   macro avg       0.70      0.69      0.70       147
weighted avg       0.72      0.72      0.72       147

0.7210884353741497
[[74 17]
 [24 32]]
